### ISSUE TITLE
Wrong pixel components values

### ISSUE THREAD

**Issue by Nyx0uf** [fleitz/ColorArt#2]
You have a problem in the following method :
-(UIColor_)_findEdgeColor:(UIImage_)image imageColors:(NSCountedSet*_)colors
{
// stuff
UIColor_ color = [UIColor colorWithRed:px.red green:px.green blue:px.blue alpha:1.0f];
// stuff
}

The values you are getting are stored in a byte, value between 0 - 255. The UIColor method wants a float between 0.0f - 1.0f.

So in most case we end up with a white color..

**Comment by fleitz** [comment]
Sweet!

Thanks for finding that, will see if that's all I need for to fix

**Comment by fleitz** [comment]
Fixed.
