### ISSUE TITLE
Calculate color very slow

### ISSUE THREAD

**Issue by nyanev** [fleitz/ColorArt#3]
Hello,

The library is great but calculate the color very slow and sometimes wrong. In the image where there is no red color the library pick red color for background.

Thanks in advanced

**Comment by fleitz** [comment]
Yeah I'm looking at improving the color detection....

I have a feeling I may be reading the alpha channel as red.

**Comment by smallqiang** [comment]
Hello,I try different pictures.But sometimes the background color is wrong.Please tell me how to modify.

**Comment by fleitz** [comment]
Not sure, but if you find the fix, submit a pull request so I can integrate.

**Comment by Nyx0uf** [comment]
if the provided image is not in RGB format, color detection can be messed up. Try to render the image in a bitmap context first then calculate the color from the resulting image.

**Comment by smallqiang** [comment]
The mac version is caculated the image size.I think this will effect.

**Comment by Nyx0uf** [comment]
I got better color results with the following :

typedef struct RGBAPixel
{
    Byte red;
    Byte green;
    Byte blue;
    Byte alpha;
} RGBAPixel;

CGColorSpaceRef cs = CGColorSpaceCreateDeviceRGB();
CGContextRef bmContext = CGBitmapContextCreate(NULL, width, height, 8, 4 \* width, cs, kCGImageAlphaNoneSkipLast);
CGContextDrawImage(bmContext, (CGRect){.origin.x = 0.0f, .origin.y = 0.0f, .size.width = width, .size.height = height}, image.CGImage);
CGColorSpaceRelease(cs);

NSCountedSet\* imageColors = [[NSCountedSet alloc] initWithCapacity:width \* height];
NSCountedSet\* edgeColors = [[NSCountedSet alloc] initWithCapacity:height];
const RGBAPixel\* pixels = (const RGBAPixel*)CGBitmapContextGetData(bmContext);

for (NSUInteger y = 0; y < height; y++)
{
    for (NSUInteger x = 0; x < width; x++)
    {
        const NSUInteger index = x + y \* width;
        RGBAPixel pixel = pixels[index];
        UIColor\* color = [[UIColor alloc] initWithRed:((CGFloat)pixel.red / 255.0f) green:((CGFloat)pixel.green / 255.0f) blue:((CGFloat)pixel.blue / 255.0f) alpha:1.0f];
        if (0 == x)
            [edgeColors addObject:color];
        [imageColors addObject:color];
    }
}
CGContextRelease(bmContext);

Don't know if speed can be improved, but with this code I managed to get 60fps scrolling in a tableView with a mixture of 50x50 and 110x110 images. The colors are computed in a background priority queue once then cached.

**Comment by fleitz** [comment]
Thanks for the code, integrated into latest commit.
